### ISSUE TITLE
Compiler plugin meta issue

### ISSUE THREAD

**Issue by kdy1997** [kdy1997/must#5]
# Todos
 - [x] ``` == != ```
   - [x] diff for string
   - [x] diff for slice / vector / array [0~32]
   - [ ] check for ```.len() == number ```
 - [ ] ``` < <= > >= ```
 - [ ] ```.contain```
   - [ ] ```slice```
 - [ ] ```.```
 - [ ] ```.is_empty()```
 - [ ] ```.is_ok(), is_err(), is_some(), is_none()```
